name = "qrcode-no-abo"
compatibility_date = "2026-03-15"
main = "worker/index.ts"

[assets]
directory = "dist"
binding = "ASSETS"
html_handling = "none"
not_found_handling = "single-page-application"
run_worker_first = true

[[kv_namespaces]]
binding = "COUNTER"
id = "ddd1ea64efbf4636b3dcf0b42ec8cf62"
